// Code generated by protoc-gen-go. DO NOT EDIT.
// source: objshpb.proto

package model

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Command struct {
	// an identifier to retrieve result
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// identifier for server to execute
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// arguments in string style
	// the command receiver should know how to interprete these values
	Args    []string          `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	Kw      map[string]string `protobuf:"bytes,4,rep,name=kw,proto3" json:"kw,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Message *any.Any          `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	//repeated google.protobuf.Any mesgArgs = 6;
	//map<string,google.protobuf.Any> mesgKw = 7;
	Kill                 bool     `protobuf:"varint,8,opt,name=kill,proto3" json:"kill,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Command) Reset()         { *m = Command{} }
func (m *Command) String() string { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()    {}
func (*Command) Descriptor() ([]byte, []int) {
	return fileDescriptor_c56ccb4321bcc0e5, []int{0}
}

func (m *Command) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Command.Unmarshal(m, b)
}
func (m *Command) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Command.Marshal(b, m, deterministic)
}
func (m *Command) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Command.Merge(m, src)
}
func (m *Command) XXX_Size() int {
	return xxx_messageInfo_Command.Size(m)
}
func (m *Command) XXX_DiscardUnknown() {
	xxx_messageInfo_Command.DiscardUnknown(m)
}

var xxx_messageInfo_Command proto.InternalMessageInfo

func (m *Command) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Command) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Command) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *Command) GetKw() map[string]string {
	if m != nil {
		return m.Kw
	}
	return nil
}

func (m *Command) GetMessage() *any.Any {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *Command) GetKill() bool {
	if m != nil {
		return m.Kill
	}
	return false
}

type Result struct {
	// id of Command of this result belongs to
	// 0 if is an unsolited message from server (aka announcement)
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	//retcode:
	// 0 completed
	// -1 this is not final result
	// 1 ~ , error code
	Retcode int32 `protobuf:"varint,2,opt,name=retcode,proto3" json:"retcode,omitempty"`
	// JSON encodeding data
	Stdout []byte `protobuf:"bytes,3,opt,name=stdout,proto3" json:"stdout,omitempty"`
	// JSON encoded data
	Stderr               string   `protobuf:"bytes,4,opt,name=stderr,proto3" json:"stderr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_c56ccb4321bcc0e5, []int{1}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Result) GetRetcode() int32 {
	if m != nil {
		return m.Retcode
	}
	return 0
}

func (m *Result) GetStdout() []byte {
	if m != nil {
		return m.Stdout
	}
	return nil
}

func (m *Result) GetStderr() string {
	if m != nil {
		return m.Stderr
	}
	return ""
}

func init() {
	proto.RegisterType((*Command)(nil), "objsh.Command")
	proto.RegisterMapType((map[string]string)(nil), "objsh.Command.KwEntry")
	proto.RegisterType((*Result)(nil), "objsh.Result")
}

func init() { proto.RegisterFile("objshpb.proto", fileDescriptor_c56ccb4321bcc0e5) }

var fileDescriptor_c56ccb4321bcc0e5 = []byte{
	// 278 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x8f, 0xcd, 0x4e, 0xc3, 0x30,
	0x10, 0x84, 0x65, 0xe7, 0xaf, 0xdd, 0x02, 0x42, 0x56, 0x55, 0x99, 0x9e, 0xac, 0x1e, 0x90, 0x4f,
	0xae, 0x54, 0x84, 0x84, 0xb8, 0x55, 0x88, 0x13, 0x37, 0xbf, 0x41, 0x42, 0x4c, 0x08, 0xf9, 0x71,
	0x65, 0x3b, 0x44, 0x79, 0x5f, 0x1e, 0x04, 0xc5, 0x49, 0x4e, 0xbd, 0xcd, 0x37, 0xda, 0xdd, 0x99,
	0x85, 0x5b, 0x9d, 0xfd, 0xd8, 0xef, 0x4b, 0x26, 0x2e, 0x46, 0x3b, 0x4d, 0x22, 0x8f, 0xfb, 0x87,
	0x42, 0xeb, 0xa2, 0x56, 0x47, 0x6f, 0x66, 0xdd, 0xd7, 0xf1, 0xdc, 0x0e, 0xd3, 0xc4, 0xe1, 0x0f,
	0x41, 0xf2, 0xa6, 0x9b, 0x26, 0x6d, 0x73, 0x72, 0x07, 0xb8, 0xcc, 0x29, 0x62, 0x88, 0x47, 0x12,
	0x97, 0x39, 0x21, 0x10, 0xb6, 0x69, 0xa3, 0x28, 0x66, 0x88, 0xaf, 0xa5, 0xd7, 0xa3, 0x97, 0x9a,
	0xc2, 0xd2, 0x80, 0x05, 0xa3, 0x37, 0x6a, 0xf2, 0x08, 0xb8, 0xea, 0x69, 0xc8, 0x02, 0xbe, 0x39,
	0xed, 0x84, 0x8f, 0x14, 0xf3, 0x4d, 0xf1, 0xd1, 0xbf, 0xb7, 0xce, 0x0c, 0x12, 0x57, 0x3d, 0x11,
	0x90, 0x34, 0xca, 0xda, 0xb4, 0x50, 0x34, 0x62, 0x88, 0x6f, 0x4e, 0x5b, 0x31, 0x15, 0x13, 0x4b,
	0x31, 0x71, 0x6e, 0x07, 0xb9, 0x0c, 0x8d, 0x59, 0x55, 0x59, 0xd7, 0x74, 0xc5, 0x10, 0x5f, 0x49,
	0xaf, 0xf7, 0xcf, 0x90, 0xcc, 0x27, 0xc9, 0x3d, 0x04, 0x95, 0x1a, 0x7c, 0xdf, 0xb5, 0x1c, 0x25,
	0xd9, 0x42, 0xf4, 0x9b, 0xd6, 0xdd, 0xd2, 0x78, 0x82, 0x57, 0xfc, 0x82, 0x0e, 0x19, 0xc4, 0x52,
	0xd9, 0xae, 0x76, 0x57, 0x4f, 0x52, 0x48, 0x8c, 0x72, 0x9f, 0x3a, 0x9f, 0xb6, 0x22, 0xb9, 0x20,
	0xd9, 0x41, 0x6c, 0x5d, 0xae, 0x3b, 0x47, 0x03, 0x86, 0xf8, 0x8d, 0x9c, 0x69, 0xf6, 0x95, 0x31,
	0x34, 0xf4, 0x31, 0x33, 0x65, 0xb1, 0xff, 0xe2, 0xe9, 0x3f, 0x00, 0x00, 0xff, 0xff, 0xab, 0x35,
	0xe7, 0x89, 0x84, 0x01, 0x00, 0x00,
}
